TSR_SIGN_NAME = {0: "Regular 10",
                 1: "Regular 20",
                 2: "Regular 30",
                 3: "Regular 40",
                 4: "Regular 50",
                 5: "Regular 60",
                 6: "Regular 70",
                 7: "Regular 80",
                 8: "Regular 90",
                 9: "Regular 100",
                 10: "Regular 110",
                 11: "Regular 120",
                 12: "Regular 130",
                 13: "Regular 140",
                 14: "NaN",
                 15: "NaN",
                 16: "NaN",
                 17: "NaN",
                 18: "NaN",
                 19: "NaN",
                 20: "NaN",
                 21: "NaN",
                 22: "Bus Stopping",
                 23: "Car Limit",
                 24: "Car Up Motor Down Diagonal",
                 25: "Minimum  Speed Limit",
                 26: "Motorcycle Limit",
                 27: "NaN",
                 28: "Electronic 10",
                 29: "Electronic 20",
                 30: "Electronic 30",
                 31: "Electronic 40",
                 32: "Electronic 50",
                 33: "Electronic 60",
                 34: "Electronic 70",
                 35: "Electronic 80",
                 36: "Electronic 90",
                 37: "Electronic 100",
                 38: "Electronic 110",
                 39: "Electronic 120",
                 40: "Electronic 130",
                 41: "Electronic 140",
                 42: "Post Exit",
                 43: "Directional Sign",
                 44: "Reserved",
                 45: "Reserved",
                 46: "No turn On Red",
                 47: "Oncoming Priority",
                 48: "No U_Turn",
                 49: "Reserved",
                 50: "NaN",
                 51: "End Of Children Area",
                 52: "Rect Pedestrians Crossing",
                 53: "Rect Rough Road",
                 54: "Divided HighWay",
                 55: "Double Reverse Curve",
                 56: "Fire Station",
                 57: "Low Clearance",
                 58: "No Outlet",
                 59: "Pedestrian Lane",
                 60: "Pedestrian Limit",
                 61: "Pedestrian Limit Diagonal",
                 62: "Shared Lane",
                 63: "Shared Separate Lane",
                 64: "Regular Gen End All Restrict",
                 66: "End Of Diversion",
                 67: "HighWay Exit 1",
                 68: "HighWay Exit 2",
                 69: "HighWay Exit 3",
                 70: "Unknown Circular Sign",
                 71: "No Parking End",
                 72: "No Parking Begin",
                 73: "No Parking Continuous",
                 74: "No Stopping End",
                 75: "No Stopping Begin",
                 76: "No Stopping Continuous",
                 77: "End No Parking Zone",
                 78: "Ausfahrt",
                 79: "End of Speed 2 digits",
                 80: "End of Speed 3 digits",
                 81: "NaN",
                 82: "NaN",
                 83: "Canceled Sign",
                 84: "NaN",
                 85: "NaN",
                 86: "NaN",
                 87: "NaN",
                 88: "NaN",
                 89: "NaN",
                 90: "NaN",
                 91: "NaN",
                 92: "Reserved",
                 93: "Reserved",
                 94: "Reserved",
                 95: "Diamond Reverse Curve Left",
                 96: "Diamond Reverse Curve Right",
                 97: "Diamond Turn Left",
                 98: "Diamond Turn Right",
                 99: "Reserved",
                 100: "Regular 5",
                 101: "Regular 15",
                 102: "Regular 25",
                 103: "Regular 35",
                 104: "Regular 45",
                 105: "Regular 55",
                 106: "Regular 65",
                 107: "Regular 75",
                 108: "Regular 85",
                 109: "Regular 95",
                 110: "Regular 105",
                 111: "Regular 115",
                 112: "Regular 125",
                 113: "Regular 135",
                 114: "Regular 145",
                 115: "Electronic 5",
                 116: "Electronic 15",
                 117: "Electronic 25",
                 118: "Electronic 35",
                 119: "Electronic 45",
                 120: "Electronic 55",
                 121: "Electronic 65",
                 122: "Electronic 75",
                 123: "Electronic 85",
                 124: "Electronic 95",
                 125: "Electronic 105",
                 126: "Electronic 115",
                 127: "Electronic 125",
                 128: "Reserved",
                 129: "Reserved",
                 130: "Horseback Riders",
                 131: "Triangular Beware Of Snow",
                 132: "Triangular Bicycle Crossing",
                 133: "Triangular Buses",
                 134: "Triangular Children",
                 135: "Triangular Congestion Hazard",
                 136: "Curve Left",
                 137: "Triangular Curve Right",
                 138: "Triangular Domestic Animals Crossing",
                 139: "Triangular Double Curve Left",
                 140: "Triangular Double Curve Right",
                 141: "Triangular Draw Bridge",
                 142: "Triangular Falling Rocks",
                 143: "Triangular General Danger",
                 144: "Triangular Guarded Railway Crossing",
                 145: "Triangular Intersection",
                 146: "Left Merge",
                 147: "Triangular Loose Gravel",
                 148: "Triangular Low Flying Aircraft",
                 149: "Triangular Pedestrians",
                 150: "Triangular Pedestrians Crossing",
                 151: "Triangular Priority",
                 152: "Right Merge",
                 153: "Reserved",
                 154: "Road Narrows",
                 155: "Road Narrows Left",
                 156: "Road Narrows Right",
                 157: "Road Work",
                 158: "Triangular Rough Road",
                 159: "Triangular Roundabout",
                 160: "Triangular Slippery When Wet",
                 161: "Triangular Steep Downgrade",
                 162: "Triangular Steep Upgrade",
                 163: "Triangular Strong Cross Wind",
                 164: "Traffic Signals",
                 165: "Two Way Traffic",
                 166: "Triangular Unguarded Railway Crossing",
                 167: "Triangular Wild Animal Crossing",
                 168: "Triangular Yield",
                 169: "Priority Road",
                 170: "End Of Priority Road",
                 171: "Regular Motorway Begin",
                 172: "Stardard Regular End Of Motorway",
                 173: "Regular Expressway Begin",
                 174: "Regular Expressway End",
                 175: "Regular Playground(Residential) Area Begin",
                 176: "Regular End Of Playground(Residential) Area",
                 177: "City Entrance(Germany Only)",
                 178: "Combined City Exit(Germany Only)",
                 179: "Tunnel",
                 180: "Diamonds Usa Add Left",
                 181: "Diamonds Usa Add Right",
                 182: "Diamonds Usa Left Lane Ends Txt",
                 183: "Diamonds Usa Right Lane Ends Txt",
                 184: "Diamonds Usa Exit Right",
                 185: "Triangular City Entrance China",
                 186: "Camera",
                 187: "Diamonds Usa Lane Merge Left Txt",
                 188: "Diamonds Usa Lane Merge Right Txt",
                 189: "Rect Priority Over Oncoming",
                 190: "Diamonds Usa Lane split Right",
                 191: "Diamonds Usa Winding Left",
                 192: "Diamonds Usa Winding Right",
                 193: "Diamonds USA Side Road Left",
                 194: "Diamonds USA Side Road Right",
                 195: "Diamond Thru Traffic Merge Txt",
                 196: "Stop Ahead",
                 197: "Loose Shoulder",
                 198: "Reserved",
                 199: "No Entrance",
                 200: "Regular No Passing Start",
                 201: "Regular End Of No Passing",
                 202: "Regular No Passing Truck Start",
                 203: "Regular End Of No Passing Truck",
                 204: "Road work with distance information",
                 205: "End Road Works Txt",
                 206: "End Construction",
                 207: "No stopping",
                 208: "No parking",
                 209: "NaN",
                 210: "Stop Sign Notification",
                 211: "Truck Limit",
                 212: "Diamonds Usa Intersection",
                 213: "Reserved",
                 214: "Diamonds Usa Danger Road Works",
                 215: "Diamonds Construction Ahead Txt",
                 216: "Bridge Ice",
                 217: "Bump",
                 218: "Reserved",
                 219: "City Entrance Black Background",
                 220: "NaN",
                 221: "NaN",
                 222: "Built Up Area",
                 223: "End of Built Up Area",
                 224: "Roundabout",
                 225: "NaN",
                 226: "NaN",
                 227: "Reserved ",
                 228: "River Bank",
                 229: "City Exit",
                 230: "Reserved",
                 231: "Reserved",
                 232: "Reserved",
                 233: "Reserved",
                 234: "Reserved",
                 235: "Reserved",
                 236: "Reserved",
                 237: "Reserved",
                 238: "Reserved",
                 239: "Reserved",
                 240: "Arrow Straight",
                 241: "Arrow Right",
                 242: "Arrow Left",
                 243: "Arrow Right Ahead",
                 244: "Arrow Left Ahead",
                 245: "Arrow No Left",
                 246: "Arrow No Right",
                 247: "Arrow Keep Left",
                 248: "Arrow Keep Right",
                 249: "Arrow Either Side",
                 250: "Road Closed",
                 251: "Reserved",
                 252: "Reserved",
                 253: "Reserved",
                 254: "Reserved",
                 255: "Invalid_Sign",
                 256: "Bicycle Lane",
                 257: "Bicycle Limit",
                 258: "Bus Limit",
                 259: "Hazardous Truck Limit",
                 260: "Height Limit",
                 261: "No Littering",
                 262: "Parking",
                 263: "Ped Diagonal Bicycle",
                 264: "NaN",
                 265: "Trucks Only",
                 266: "Weight Limit",
                 267: "Width Limit",
                 268: "Motor Up Car Down",
                 269: "Low Emission Zone",
                 270: "End Of Low Emission Zone",
                 271: "End Of Toll",
                 272: "Round Road Number",
                 273: "Reserved",
                 274: "Reserved",
                 275: "Reserved",
                 276: "Reserved",
                 277: "Reserved",
                 278: "Reserved",
                 279: "Reserved",
                 280: "Reserved",
                 281: "Reserved",
                 282: "Reserved",
                 283: "Reserved",
                 284: "Reserved",
                 285: "Reserved",
                 286: "Reserved",
                 287: "Reserved",
                 288: "Reserved",
                 289: "Reserved",
                 290: "Reserved",
                 291: "Reserved",
                 292: "Reserved",
                 293: "Reserved",
                 294: "Reserved",
                 295: "Reserved",
                 296: "Reserved",
                 297: "Reserved",
                 298: "Reserved",
                 299: "Reserved",
                 300: "Reserved",
                 301: "Reserved",
                 302: "Maximum Axle Load",
                 303: "Reserved",
                 304: "Reserved",
                 305: "Reserved",
                 306: "Reserved",
                 307: "Reserved",
                 308: "Reserved",
                 309: "Reserved",
                 310: "Reserved",
                 311: "Reserved",
                 312: "Reserved",
                 313: "ETC",
                 314: "ETC_TOLL",
                 315: "TOLL",
                 316: "CONSTRUCTION_ARROW_RIGHT",
                 317: "CONSTRUCTION_ARROW_LEFT",
                 318: "DIRECTIONAL_SIGN_JP",
                 319: "ROADWORK_JP",
                 320: "CONSTRUCTION_JP",
                 321: "ROADWORK_ELECT_JP",
                 322: "ROADWORK_RIGHT_JP",
                 323: "Reserved",
                 324: "Reserved",
                 325: "Reserved",
                 326: "Reserved",
                 328: "Reserved",
                 329: "Reserved",
                 330: "Reserved",
                 331: "Reserved",
                 332: "Reserved",
                 333: "Reserved",
                 334: "Reserved",
                 335: "Reserved",
                 336: "Reserved",
                 337: "Reserved",
                 338: "Reserved",
                 339: "Reserved",
                 340: "Reserved",
                 341: "Reserved",
                 342: "Reserved",
                 343: "Reserved",
                 344: "Reserved",
                 345: "Reserved",
                 346: "Reserved",
                 347: "Reserved",
                 348: "Reserved",
                 349: "Reserved",
                 350: "Reserved",
                 351: "Reserved",
                 352: "Reserved",
                 353: "Reserved",
                 354: "Reserved",
                 355: "Reserved",
                 356: "Reserved",
                 357: "Reserved",
                 358: "Reserved",
                 359: "Reserved",
                 360: "Reserved",
                 361: "Reserved",
                 362: "Reserved",
                 363: "Reserved",
                 364: "Reserved",
                 365: "Reserved",
                 366: "Reserved",
                 367: "Reserved",
                 368: "Reserved",
                 369: "Reserved",
                 370: "Reserved",
                 371: "Reserved",
                 372: "Reserved",
                 373: "Reserved",
                 374: "Reserved",
                 375: "Reserved",
                 376: "Reserved",
                 377: "Reserved",
                 378: "Reserved",
                 379: "Reserved",
                 380: "Reserved",
                 381: "Reserved",
                 382: "Reserved",
                 383: "Reserved",
                 384: "Reserved",
                 385: "Reserved",
                 386: "Reserved",
                 387: "Reserved",
                 388: "Reserved",
                 389: "Reserved",
                 390: "Reserved",
                 391: "Reserved",
                 392: "Reserved",
                 393: "Reserved",
                 394: "Reserved",
                 395: "Reserved",
                 396: "Reserved",
                 397: "Reserved",
                 398: "Reserved",
                 399: "Electrical Off"
                 }
